services:
  postgres:
    image: postgres:16-alpine
    container_name: bap_postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: formbuilder
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Aryan2003
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d formbuilder"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
